import {
	PriorityCategory,
	PriorityLevel,
	Task,
} from "@/prisma/generated/prisma";
import dayjs from "dayjs";

const baseDate = dayjs().startOf("day").add(9, "hour"); // 9:00 AM today

export const testTasks: Task[] = [
	{
		id: "1",
		userId: "1",
		title: "Morning Standup",
		description: "Daily team sync meeting",
		priorityLevel: PriorityLevel.MED,
		priorityScore: 3,
		priorityCategory: PriorityCategory.MED,
		start: baseDate.toISOString(),
		end: baseDate.add(30, "minute").toISOString(),
		estimatedDuration: "00:30",
		isHardDeadline: true,
		isRecurring: true,
		completed: false,
	},
	{
		id: "2",
		userId: "1",
		title: "Code Review",
		description: "Review PRs assigned to you",
		priorityLevel: PriorityLevel.HIGH,
		priorityScore: 5,
		priorityCategory: PriorityCategory.HIGH,
		start: baseDate.add(1, "hour").toISOString(),
		end: baseDate.add(2, "hour").toISOString(),
		estimatedDuration: "01:00",
		isHardDeadline: false,
		isRecurring: false,
		completed: false,
	},
	{
		id: "3",
		userId: "1",
		title: "Write Documentation",
		description: "Update API docs for new endpoints",
		priorityLevel: PriorityLevel.LOW,
		priorityScore: 1,
		priorityCategory: PriorityCategory.LOW,
		start: baseDate.add(2, "hour").toISOString(),
		dueDateTime: baseDate.add(3, "hour").toISOString(),
		estimatedDuration: "01:00",
		isHardDeadline: false,
		isRecurring: false,
		completed: false,
	},
	{
		id: "4",
		userId: "1",
		title: "Client Call",
		description: "Discuss project requirements",
		priorityLevel: PriorityLevel.CRIT,
		priorityScore: 8,
		priorityCategory: PriorityCategory.CRIT,
		start: baseDate.add(4, "hour").toISOString(),
		end: baseDate.add(5, "hour").toISOString(),
		estimatedDuration: "01:00",
		isHardDeadline: true,
		isRecurring: false,
		completed: false,
	},
	{
		id: "5",
		userId: "1",
		title: "Design Review",
		description: "Review new UI mockups",
		priorityLevel: PriorityLevel.MED,
		priorityScore: 2,
		priorityCategory: PriorityCategory.MED,
		start: baseDate.add(5, "hour").toISOString(),
		end: baseDate.add(6, "hour").toISOString(),
		estimatedDuration: "01:00",
		isHardDeadline: false,
		isRecurring: false,
		completed: false,
	},
];
