import dayjs from "dayjs";
import {type AutomaticTask, PriorityCategory, PriorityLevel, TaskType,} from "@prisma/client";

// Set baseDate to today
const baseDate: dayjs.Dayjs = dayjs()
	.set("hour", 8)
	.set("minute", 0)
	.set("second", 0)
	.set("millisecond", 0);

export const testTasks: AutomaticTask[] = [
	{
		id: "1",
		userId: "1",
		taskType: TaskType.AUTOMATIC,
		title: "Morning Standup",
		description: "Daily team sync meeting",
		priorityLevel: PriorityLevel.MED,
		priorityScore: 3,
		priorityCategory: PriorityCategory.MED,
		start: baseDate.toDate(),
		end: baseDate.add(30, "minute").toDate(),
		dueDateTime: baseDate.add(30, "minute").toDate(),
		estimatedDuration: 30,
		isHardDeadline: true,
		isRecurring: true,
		completed: false,
		isStatic: true,
	},
	{
		id: "2",
		userId: "1",
		taskType: TaskType.AUTOMATIC,
		title: "Code Review",
		description: "Review PRs assigned to you",
		priorityLevel: PriorityLevel.HIGH,
		priorityScore: 5,
		priorityCategory: PriorityCategory.HIGH,
		start: baseDate.add(1, "hour").toDate(),
		end: baseDate.add(1, "day").add(1, "hour").toDate(),
		dueDateTime: baseDate.add(1, "day").add(1, "hour").toDate(),
		estimatedDuration: 60,
		isHardDeadline: false,
		isRecurring: false,
		completed: false,
		isStatic: true,
	},
	{
		id: "3",
		userId: "1",
		taskType: TaskType.AUTOMATIC,
		title: "Write Documentation",
		description: "Update API docs for new endpoints",
		priorityLevel: PriorityLevel.LOW,
		priorityScore: 1,
		priorityCategory: PriorityCategory.LOW,
		start: baseDate.add(2, "hour").toDate(),
		end: baseDate.add(2, "day").add(1, "hour").toDate(),
		dueDateTime: baseDate.add(2, "day").add(1, "hour").toDate(),
		estimatedDuration: 60,
		isHardDeadline: false,
		isRecurring: false,
		completed: false,
		isStatic: true,
	},
	{
		id: "4",
		userId: "1",
		taskType: TaskType.AUTOMATIC,
		title: "Client Call",
		description: "Discuss project requirements",
		priorityLevel: PriorityLevel.CRIT,
		priorityScore: 8,
		priorityCategory: PriorityCategory.CRIT,
		start: baseDate.add(3, "hour").toDate(),
		end: baseDate.add(3, "day").add(1, "hour").toDate(),
		dueDateTime: baseDate.add(3, "day").add(1, "hour").toDate(),
		estimatedDuration: 60,
		isHardDeadline: true,
		isRecurring: false,
		completed: false,
		isStatic: true,
	},
	{
		id: "5",
		userId: "1",
		taskType: TaskType.AUTOMATIC,
		title: "Design Review",
		description: "Review new UI mockups",
		priorityLevel: PriorityLevel.MED,
		priorityScore: 2,
		priorityCategory: PriorityCategory.MED,
		start: baseDate.add(4, "hour").toDate(),
		end: baseDate.add(4, "day").add(1, "hour").toDate(),
		dueDateTime: baseDate.add(4, "day").add(1, "hour").toDate(),
		estimatedDuration: 60,
		isHardDeadline: false,
		isRecurring: false,
		completed: false,
		isStatic: true,
	},
];
